service: leve-saude-api

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getAgenda:
    handler: src/functions/getAgenda.handler
    events:
      - httpApi:
          path: /agendas
          method: get

  createAgendamento:
    handler: src/functions/createAgendamento.handler
    events:
      - httpApi:
          path: /agendamento
          method: post

plugins:
  - serverless-offline