service: leve-saude-api

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  stage: dev

functions:
  getAgenda:
    handler: src/functions/getAgenda.handler
    events:
      - httpApi:
          path: agenda
          method: get


plugins:
  - serverless-offline